version: "3"

services:
  test_controller:
    build:
      context: test_controller
      dockerfile: Dockerfile
    container_name: 'test_controller'
    working_dir: '/home/target/'
    tty: true
    environment: 
      - HOST_WORK_DIR
      - HOST_JENKINS_WORKSPACE
      - CONTAINER_JENKINS_WORKSPACE
      - HOST_TEST_CONTROLLER_WORKSPACE
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins_workspace:/home/workspace
    restart: always
    ports:
      - 8080:8080


  chrome:
    image: selenium/standalone-chrome
    ports:
      - 5900:5900
      - 4444:4444
    volumes:
      - ./shm_chrome:/dev/shm

  firefox:
    image: selenium/standalone-firefox-debug:3.141.59
    ports:
      - 5901:5900
      - 4445:4444
    volumes:
      - ./shm_firefox:/dev/shm


  opera:
    image: selenium/standalone-opera
    ports:
      - 5902:5900
      - 4446:4444
    volumes:
      - ./shm_opera:/dev/shm

  tester_cs:
    build:
      context: tester_package/tester_cs
      dockerfile: Dockerfile
    environment: 
      - HOST_JENKINS_WORKSPACE
      - HOST_TEST_CONTROLLER_WORKSPACE
    container_name: 'cs_test'
    working_dir: /home/web
    tty: true
    volumes:
      - ./tester_package/tester_cs/web:/home/web
      - ./jenkins_workspace:/home/build
    depends_on: 
      - test_controller

          