version: "3"

services:
  test_controller:
    build:
      context: test_controller
      dockerfile: Dockerfile
    container_name: 'test_controller'
    working_dir: '/home/target/'
    tty: true
    environment: 
      - HOST_WORK_DIR
      - HOST_JENKINS_WORKSPACE
      - CONTAINER_JENKINS_WORKSPACE
      - HOST_TEST_CONTROLLER_WORKSPACE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
      - ${HOST_TEST_CONTROLLER_WORKSPACE}:/home/target
    restart: always
    ports:
      - 8080:8080


  chrome:
    image: selenium/standalone-chrome
    ports:
      - 5900:5900
      - 4444:4444
    volumes:
      - ./shm_chrome:/dev/shm

  firefox:
    image: selenium/standalone-firefox-debug:3.141.59
    ports:
      - 5901:5900
      - 4445:4444
    volumes:
      - ./shm_firefox:/dev/shm


  opera:
    image: selenium/standalone-opera
    ports:
      - 5902:5900
      - 4446:4444
    volumes:
      - ./shm_opera:/dev/shm

              