version: "3"

services:
  test_controller:
    build:
      context: test_controller
      dockerfile: Dockerfile
    container_name: 'test_controller'
    working_dir: '/home/target/'
    tty: true
    environment: 
      - HOST_WORK_DIR
      - TEST_WORK_DIR
      - CS_TEST_WORK_DIR
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tester_package:/home/target
      - ./jenkins_home:/var/jenkins_home
    restart: always
    ports:
      - 8080:8080


  hub:
    image: selenium/hub
    ports:
      - '4444:4444'
  chrome:
    image: selenium/standalone-chrome
    ports:
      - 5900:5900
    volumes:
      - ./shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

  firefox:
    image: selenium/standalone-firefox-debug:3.141.59
    ports:
      - 5901:5900
    volumes:
      - ./shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

