version: "3"

services:
  tester_cs:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - TESTER_CS_REPOGITORY
      - HOST_WORK_DIR
    container_name: 'cs_test'
    working_dir: '/home/build/'
    tty: true
    # Note: volume for 2 generation container
    # https://www.nullpo.io/2020/05/27/docker-dood-volume/
    volumes:
      - ${CS_TEST_WORK_DIR}:/home/build
